tap "chrokh/tap"
tap "cjbassi/gotop"
tap "danger/tap"
tap "datawire/blackbird"
tap "garethr/kubeval"
tap "getantibody/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "ibdecodable/tap"
tap "kateinoigakukun/tap"
tap "kylef/formulae"
tap "mono0926/license-plist"
tap "universal-ctags/universal-ctags"
tap "vapor/tap"
tap "yonaskolb/beak", "https://github.com/yonaskolb/Beak.git"
cask "abstract"
cask "osxfuse"
cask "sketch"
brew "ack"
brew "autoconf"
brew "autojump"
brew "bash"
brew "bash-completion"
brew "bat"
brew "bazaar"
brew "openssl"
brew "readline"
brew "python"
brew "black"
brew "brew-cask-completion"
brew "carthage"
brew "cask"
brew "chisel"
brew "clang-format"
brew "cloc"
brew "cmus"
brew "cocoapods"
brew "coreutils"
brew "cppcheck"
brew "ctags", args: ["HEAD"]
brew "curl"
brew "wget"
brew "dasht"
brew "go"
brew "dep"
brew "direnv"
brew "dnsmasq"
brew "docker-completion"
brew "docker-compose"
brew "node"
brew "eslint"
brew "fd"
brew "ffmpeg"
brew "findutils"
brew "flawfinder"
brew "fzf"
brew "gcc"
brew "git"
brew "git-extras"
brew "gnu-sed"
brew "grep"
brew "hadolint"
brew "httpie"
brew "hub"
brew "hugo"
brew "imagemagick@6", link: true
brew "jq"
brew "jsonlint"
brew "kubernetes-cli"
brew "kustomize"
brew "m-cli"
brew "marathon-swift"
brew "mariadb-connector-c"
brew "mas"
brew "memcached"
brew "mercurial"
brew "mergepbx"
brew "mint"
brew "mongodb"
brew "moreutils"
brew "mosh"
brew "mysql@5.6", link: true
brew "ncdu"
brew "neovim"
brew "nmap"
brew "nodebrew"
brew "pandoc"
brew "pkg-config"
brew "postgresql"
brew "pv"
brew "ruby-build"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "redis"
brew "rename"
brew "ripgrep"
brew "screen"
brew "shellcheck"
brew "shfmt"
brew "skaffold"
brew "sourcekitten"
brew "sourcery"
brew "swiftformat"
brew "swiftgen"
brew "swiftlint"
brew "terminal-notifier"
brew "the_platinum_searcher"
brew "the_silver_searcher"
brew "tldr"
brew "tmux"
brew "tokei"
brew "trash"
brew "tree"
brew "xctool"
brew "yamllint"
brew "youtube-dl"
brew "zopfli"
brew "zsh"
brew "zsh-autosuggestions"
brew "cjbassi/gotop/gotop"
brew "danger/tap/danger-swift"
brew "datawire/blackbird/telepresence"
brew "garethr/kubeval/kubeval"
brew "getantibody/tap/antibody"
brew "kateinoigakukun/tap/iblinter"
brew "kylef/formulae/swiftenv"
brew "mono0926/license-plist/license-plist"
brew "vapor/tap/vapor"
brew "yonaskolb/beak/beak"
cask "alfred"
cask "arduino"
cask "caffeine"
cask "chromedriver"
cask "docker"
cask "fastlane"
cask "font-source-code-pro"
cask "font-source-code-pro-for-powerline"
cask "font-source-sans-pro"
cask "font-source-serif-pro"
cask "font-sourcecodepro-nerd-font"
cask "font-sourcecodepro-nerd-font-mono"
cask "iterm2"
cask "java"
cask "minikube"
cask "qlcolorcode"
cask "qlmarkdown"
cask "quicklook-csv"
cask "quicklook-json"
cask "spectacle"
cask "spotify"
cask "virtualbox"
cask "visual-studio-code"
mas "1Password 7", id: 1333542190
mas "Affinity Designer", id: 824171161
mas "Battery Health", id: 490192174
mas "Bear", id: 1091189122
mas "DevCleaner", id: 1388020431
mas "Don't Sleep!", id: 466314666
mas "InjectionIII", id: 1380446739
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PiPifier", id: 1160374471
mas "Pixelmator", id: 407963104
mas "Pocket", id: 568494494
mas "Realm Browser", id: 1007457278
mas "Reeder", id: 880001334
mas "Spark", id: 1176895641
mas "The Unarchiver", id: 425424353
mas "Things3", id: 904280696
mas "XLIFFTool", id: 1074282695
