- name: Create neovim config directory
  file:
    path: "~/.config/nvim"
    state: directory
    mode: "0755"

- name: Symlink vimrc to nvim/init.vim
  file:
    src: "{{ dotfiles_home }}/neovim/init.vim"
    dest: "~/.config/nvim/init.vim"
    state: link
